aya-template-bpf/Cargo.toml - remove branch attribute
Remove `branch = "main"` which currencly (with rust 1.55) causes the following error:
```
$ cargo +nightly build --target=bpfel-unknown-none -Z build-std=core
error: failed to parse manifest at `/home/vagrant/gh/alessandrod/throwaway-example/aya-template-bpf/Cargo.toml`

Caused by:
  key `branch` is ignored for dependency (aya-bpf).
```